# Generated by Django 4.2 on 2025-11-07 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Name displayed during gameplay', max_length=50)),
                ('guest_session', models.UUIDField(blank=True, default=uuid.uuid4, help_text='Unique identifier for guest players', null=True)),
                ('total_games', models.IntegerField(default=0, help_text='Total number of games played')),
                ('total_score', models.BigIntegerField(default=0, help_text='Cumulative score across all games')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this player was created')),
                ('user', models.OneToOneField(blank=True, help_text='Link to user account if player is registered', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'ordering': ['-created_at'],
            },
        ),
    ]
