#!/usr/bin/env python3
"""
IP Configuration Updater
Detects current network IP and updates configuration files
"""

import socket
import os
import re
from pathlib import Path

def get_local_ip():
    """
    Get the current local network IP address.
    This finds the IP that would be used to connect to the internet.
    """
    try:
        # Create a socket to find the default route IP
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        # Connect to a public DNS server (doesn't actually send data)
        s.connect(("8.8.8.8", 80))
        ip = s.getsockname()[0]
        s.close()
        return ip
    except Exception as e:
        print(f"Error detecting IP: {e}")
        return None

def update_env_file(ip):
    """
    Update the frontend .env file with the detected IP
    """
    env_path = Path(__file__).parent / 'frontend' / '.env'

    env_content = f"""# Vite environment variables
# Auto-generated by update_ip.py
# Run 'python update_ip.py' when switching networks

# Backend API configuration
VITE_API_HOST={ip}
VITE_API_PORT=8000

# WebSocket configuration
VITE_WS_HOST={ip}
VITE_WS_PORT=8000
"""

    try:
        with open(env_path, 'w') as f:
            f.write(env_content)
        print(f"✓ Updated {env_path}")
        return True
    except Exception as e:
        print(f"✗ Error updating .env file: {e}")
        return False

def update_allowed_hosts(ip):
    """
    Add IP to Django ALLOWED_HOSTS if not already present
    """
    settings_path = Path(__file__).parent / 'backend' / 'settings.py'

    try:
        with open(settings_path, 'r') as f:
            content = f.read()

        # Check if IP is already in ALLOWED_HOSTS
        if f"'{ip}'" in content or f'"{ip}"' in content:
            print(f"✓ IP {ip} already in ALLOWED_HOSTS")
            return True

        # Find the ALLOWED_HOSTS line and add the IP
        import re
        pattern = r"(ALLOWED_HOSTS\s*=\s*\[)([^\]]*?)(\])"

        def add_ip(match):
            start = match.group(1)
            hosts = match.group(2)
            end = match.group(3)

            # Add the new IP to the list
            if hosts.strip():
                return f"{start}{hosts}, '{ip}'{end}"
            else:
                return f"{start}'{ip}'{end}"

        new_content = re.sub(pattern, add_ip, content, count=1)

        if new_content != content:
            with open(settings_path, 'w') as f:
                f.write(new_content)
            print(f"✓ Added {ip} to ALLOWED_HOSTS")
            return True
        else:
            print(f"⚠ Could not find ALLOWED_HOSTS in settings.py")
            return True

    except Exception as e:
        print(f"✗ Error updating ALLOWED_HOSTS: {e}")
        return False

def main():
    """
    Main function to detect IP and update configuration
    """
    print("=" * 60)
    print("Jeopardy Server IP Configuration")
    print("=" * 60)

    # Get current IP
    ip = get_local_ip()

    if not ip:
        print("\n✗ Could not detect network IP address")
        print("  Make sure you're connected to a network")
        return 1

    print(f"\n📡 Detected IP Address: {ip}")
    print(f"\n🌐 Access Points:")
    print(f"  Frontend: http://{ip}:5173")
    print(f"  Backend:  http://{ip}:8000")
    print(f"  WebSocket: ws://{ip}:8000/ws/")

    # Update configuration files
    print("\n📝 Updating configuration files...")

    success = True
    success &= update_env_file(ip)
    success &= update_allowed_hosts(ip)

    if success:
        print("\n✅ Configuration updated successfully!")
        print("\n📋 Next steps:")
        print("  1. Restart the frontend dev server (npm run dev)")
        print("  2. Make sure backend is running: python manage.py runserver 0.0.0.0:8000")
        print(f"  3. Access from other devices: http://{ip}:5173")
        return 0
    else:
        print("\n✗ Some updates failed. Check errors above.")
        return 1

if __name__ == '__main__':
    exit(main())
