# Generated by Django 4.2 on 2025-11-07 00:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Category name (e.g., 'POTENT POTABLES')", max_length=200)),
                ('round_type', models.CharField(choices=[('single', 'Single Jeopardy'), ('double', 'Double Jeopardy'), ('final', 'Final Jeopardy')], help_text='Which round this category appears in', max_length=20)),
                ('position', models.IntegerField(help_text='Position on board (0-5 for regular rounds)')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['episode', 'round_type', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text="The clue text (what's read to players)")),
                ('answer', models.TextField(help_text='The correct answer')),
                ('value', models.IntegerField(help_text='Point value (200, 400, 600, 800, 1000, or 400, 800, etc.)')),
                ('position', models.IntegerField(help_text='Position within category (0-4)')),
                ('is_daily_double', models.BooleanField(default=False, help_text='Is this clue a Daily Double?')),
                ('category', models.ForeignKey(help_text='Which category this clue belongs to', on_delete=django.db.models.deletion.CASCADE, to='games.category')),
            ],
            options={
                'verbose_name': ('Clue',),
                'verbose_name_plural': 'Clues',
                'ordering': ['category', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.IntegerField(help_text='Season number (e.g., 1, 2, 3)')),
                ('episode_number', models.IntegerField(help_text='Episode number within season')),
                ('air_date', models.DateField(blank=True, help_text='Original air date (if known)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Episode',
                'verbose_name_plural': 'Episodes',
                'ordering': ['season_number', 'episode_number'],
                'unique_together': {('season_number', 'episode_number')},
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique game identifier (used in URLs)', unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for Players'), ('active', 'Game in Progress'), ('paused', 'Paused'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='waiting', help_text='Current game status', max_length=20)),
                ('current_round', models.CharField(choices=[('single', 'Single Jeopardy'), ('double', 'Double Jeopardy'), ('final', 'Final Jeopardy')], default='single', help_text='Which round the game is currently in', max_length=20)),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Game configuration (optional rules, timing, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('episode', models.ForeignKey(help_text='Which episode this game users', on_delete=django.db.models.deletion.PROTECT, to='games.episode')),
                ('host', models.ForeignKey(help_text='Player who is hosting this game', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_games', to='users.player')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_number', models.IntegerField(help_text='Position (1, 2, or 3)')),
                ('score', models.IntegerField(default=0, help_text='Current score in this game')),
                ('final_wager', models.IntegerField(blank=True, help_text='Wager amount for Final Jeopardy', null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(help_text='Which game this participant is in', on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('player', models.ForeignKey(help_text='Which player this is', on_delete=django.db.models.deletion.CASCADE, to='users.player')),
            ],
            options={
                'verbose_name': 'Game Participant',
                'verbose_name_plural': 'Game Paticipants',
                'ordering': ['game', 'player_number'],
                'unique_together': {('game', 'player_number')},
            },
        ),
        migrations.CreateModel(
            name='GameAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this action occurred')),
                ('action_type', models.CharField(help_text='Type of action (buzz, answer, score_change, etc.)', max_length=50)),
                ('data', models.JSONField(default=dict, help_text='Action-specific data stored as JSON')),
                ('server_timestamp_us', models.BigIntegerField(help_text='Microsecond precision timestamp for buzzer timing')),
                ('game', models.ForeignKey(help_text='Which game this action occurred in', on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('participant', models.ForeignKey(blank=True, help_text='Which participant performed this action', null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.gameparticipant')),
            ],
            options={
                'verbose_name': 'Game Action',
                'verbose_name_plural': 'Game Actions',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ClueReveal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revealed_at', models.DateTimeField(auto_now_add=True, help_text='When the clue was revealed')),
                ('correct', models.BooleanField(blank=True, help_text='Was the answer correct? (None = not answered yet)', null=True)),
                ('buzz_winner', models.ForeignKey(blank=True, help_text='Who buzzed in first and got to answer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_buzzes', to='games.gameparticipant')),
                ('clue', models.ForeignKey(help_text='Which clue was revealed', on_delete=django.db.models.deletion.PROTECT, to='games.clue')),
                ('game', models.ForeignKey(help_text='Which game this clue was revealed in', on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('revealed_by', models.ForeignKey(blank=True, help_text='Who selected this clue (host picks for them)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.gameparticipant')),
            ],
            options={
                'verbose_name': 'Clue Reveal',
                'verbose_name_plural': 'Clue Reveals',
                'ordering': ['revealed_at'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='episode',
            field=models.ForeignKey(help_text='Which episode this category belongs to', on_delete=django.db.models.deletion.CASCADE, to='games.episode'),
        ),
    ]
