# Generated by Django 4.2.16 on 2026-01-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameparticipant',
            name='player_number',
            field=models.IntegerField(help_text='Position (1-6)'),
        ),
    ]
